FORMAT: 1A
HOST: https://www.documentosonline.cl/

# Docs Online

Esta es una API sencilla, para pedir la entrega de un documento PDF a partir de DTE, en formato XML.

## Enviar el XML [/dte/hgen/token]

### Envio de XML [POST]

+ Request (u'multipart/form-data; boundary=33b4531a79be4b278de5f5688fab7701')

        {
            "file_upload": "Archivo xml"
        }

+ Response 200 (application/json)

        {
            "token": "token para rescatar el documento",
        }
        

## Obtener el PDF a partir del token [/dte/jget]

### Envio del Token [POST]

+ Request (application/json)

        {
            "params": {
                "token": "token obtenido desde /dte/hgen/token"
            }
        }

+ Response 200 (application/json)

    + Body

            {
                "result": {
                    "pdf": "archivo pdf codificado en base64"
                }
            }
            

## Obtener email de intercambio y giros con el rut [/partner/jget]

### Envio del RUT [POST]

+ Request
    + Headers
    
            Content-Type: application/json
            Charset: utf-8
            Authorization: Basic consiga_su_token_registrando_en_www_documentosonline_cl

    + Body
    
            {
                "params": {
                    "vat": "99999999-9"
                }
            }
        
+ Response 200 (application/json)

    + Body
    
            {
                'jsonrpc': u'2.0',
                'id': None, 
                'result': {
                    'partner_activities_ids': {
                        'code': '999999',
                        'name': 'Nombre de actividad'
                    }, 
                    'name': 'Nombre Razon Social',
                    'dte_resolution_date': 'AAAA-MM-DD',
                    'dte_email': 'mail@example.com',
                    'email': 'mail@example.com',
                    'vat': 'CL99999999X',
                    'dte_resolution_number': '999'
                }
            }